# Generated by Django 5.2 on 2025-04-28 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('vehicle_class', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('cylinder_capacity', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=20)),
                ('origin_country', models.CharField(max_length=50)),
                ('wheel_base', models.IntegerField()),
                ('seating_capacity', models.IntegerField()),
                ('condition', models.CharField(max_length=50)),
                ('availability', models.BooleanField()),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetail',
            fields=[
                ('chassis_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('engine_no', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('modification', models.TextField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_location', models.CharField(blank=True, max_length=200, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.IntegerField(default=1)),
                ('purchase_date', models.DateField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRegistration',
            fields=[
                ('vr_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=30)),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_location', models.CharField(max_length=50)),
                ('register_date', models.DateField()),
                ('special_note', models.TextField(blank=True, null=True)),
                ('chassis_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicledetail')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_location', models.CharField(blank=True, max_length=200, null=True)),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sold_date', models.DateField()),
                ('chassis_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicledetail')),
            ],
        ),
    ]
