# Generated by Django 5.2 on 2025-05-16 12:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('origin_country', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='VehicleParts_Sales',
            fields=[
                ('vps_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehicle Parts Sale',
                'verbose_name_plural': 'Vehicle Parts Sales',
            },
        ),
        migrations.CreateModel(
            name='VehicleParts',
            fields=[
                ('vp_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=255)),
                ('part_no', models.IntegerField()),
                ('bn_rc', models.CharField(max_length=50)),
                ('mf_date', models.DateField(blank=True, null=True)),
                ('warranty', models.PositiveIntegerField()),
                ('made_in', models.CharField(max_length=50)),
                ('stock_place', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='vehicle_parts.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Part',
                'verbose_name_plural': 'Vehicle Parts',
            },
        ),
        migrations.CreateModel(
            name='VehicleParts_Purchases',
            fields=[
                ('vpp_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=100)),
                ('arrival_method', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.PositiveIntegerField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('vp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='vehicle_parts.vehicleparts')),
            ],
            options={
                'verbose_name': 'Vehicle Parts Purchase',
                'verbose_name_plural': 'Vehicle Parts Purchases',
            },
        ),
        migrations.CreateModel(
            name='VehicleParts_SaleItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('vp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='vehicle_parts.vehicleparts')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vehicle_parts.vehicleparts_sales')),
            ],
            options={
                'verbose_name': 'Vehicle Parts Sale Item',
                'verbose_name_plural': 'Vehicle Parts Sale Items',
            },
        ),
        migrations.AddConstraint(
            model_name='vehicleparts',
            constraint=models.UniqueConstraint(fields=('vehicle', 'part_name'), name='unique_vehicle_part'),
        ),
        migrations.AddConstraint(
            model_name='vehicleparts_saleitems',
            constraint=models.UniqueConstraint(fields=('sale', 'vp'), name='unique_sale_part'),
        ),
    ]
